apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_metrics:9090
    isDefault: true
    editable: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: "TheDarkFox99"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true