"""add: new table order_products

Revision ID: 0003ecefaa49
Revises: e7b17a301d94
Create Date: 2025-05-02 19:36:16.374410

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0003ecefaa49"
down_revision = "e7b17a301d94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Order_id_product_fkey", "Order", type_="foreignkey")
    op.drop_column("Order", "id_product")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Order",
        sa.Column(
            "id_product", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "Order_id_product_fkey", "Order", "Product", ["id_product"], ["id"]
    )
    # ### end Alembic commands ###
