"""Update tables #2

Revision ID: 0090c127916f
Revises: e4de10453592
Create Date: 2024-09-05 21:26:26.777216

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0090c127916f"
down_revision = "e4de10453592"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
