"""add: type_product_models

Revision ID: 00e020995af3
Revises: 20f4849795fc
Create Date: 2025-02-10 04:10:25.234506

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00e020995af3"
down_revision = "20f4849795fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Producttypemodels",
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id_type_model", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_type_model"],
            ["Typemoto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Producttypemodels")
    # ### end Alembic commands ###
