"""Update tables

Revision ID: 1427b5adf155
Revises: 62a6b25fdcc7
Create Date: 2024-06-10 00:32:22.378939

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1427b5adf155"
down_revision = "62a6b25fdcc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product",
        "photo_product",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product",
        "photo_product",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    # ### end Alembic commands ###
