"""Add product category table

Revision ID: 162f1975f418
Revises: ef6337b7669b
Create Date: 2024-09-05 20:54:32.824140

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "162f1975f418"
down_revision = "ef6337b7669b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
