"""add: order_products table

Revision ID: 172292870c95
Revises: 0003ecefaa49
Create Date: 2025-05-02 19:47:06.058050

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "172292870c95"
down_revision = "0003ecefaa49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Orderproducts",
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_order"],
            ["Order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Orderproducts")
    # ### end Alembic commands ###
