"""add cascade operation on order table

Revision ID: 1c00ae8f661b
Revises: ee7e9fbe5401
Create Date: 2025-05-02 22:01:26.362752

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c00ae8f661b"
down_revision = "ee7e9fbe5401"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
