"""update product table

Revision ID: 1cbf0a317828
Revises: 444ea7d5fc2a
Create Date: 2024-11-30 20:41:18.483794

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cbf0a317828"
down_revision = "444ea7d5fc2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Product", "photo_product")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Product",
        sa.Column(
            "photo_product", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
