"""add: type_product_models

Revision ID: 20f4849795fc
Revises: 894bea32b257
Create Date: 2025-02-10 04:05:10.818544

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20f4849795fc"
down_revision = "894bea32b257"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Product_type_pr", table_name="Product")
    op.drop_constraint("Product_type_pr_fkey", "Product", type_="foreignkey")
    op.drop_column("Product", "type_pr")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Product",
        sa.Column("type_pr", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "Product_type_pr_fkey",
        "Product",
        "Typemoto",
        ["type_pr"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index("ix_Product_type_pr", "Product", ["type_pr"], unique=False)
    # ### end Alembic commands ###
