"""Add index, unique in tables

Revision ID: 23c9f0693868
Revises: 3f762e395067
Create Date: 2024-06-06 22:56:58.296796

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23c9f0693868"
down_revision = "3f762e395067"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Admin_email_admin_key", "Admin", type_="unique")
    op.create_index(
        op.f("ix_Admin_email_admin"), "Admin", ["email_admin"], unique=True
    )
    op.create_index(
        op.f("ix_Product_title_product"),
        "Product",
        ["title_product"],
        unique=True,
    )
    op.create_index(
        op.f("ix_User_email_user"), "User", ["email_user"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_User_email_user"), table_name="User")
    op.drop_index(op.f("ix_Product_title_product"), table_name="Product")
    op.drop_index(op.f("ix_Admin_email_admin"), table_name="Admin")
    op.create_unique_constraint(
        "Admin_email_admin_key", "Admin", ["email_admin"]
    )
    # ### end Alembic commands ###
