"""update: user table

Revision ID: 244c8280f812
Revises: 922c75d093e0
Create Date: 2025-01-23 15:31:19.775778

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "244c8280f812"
down_revision = "922c75d093e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("date_birthday", sa.Date(), nullable=True))
    op.add_column("User", sa.Column("address", sa.Text(), nullable=True))
    op.drop_index("ix_User_country_address", table_name="User")
    op.drop_index("ix_User_name_company_address", table_name="User")
    op.drop_column("User", "country_address")
    op.drop_column("User", "surname_user_address")
    op.drop_column("User", "name_user_address")
    op.drop_column("User", "address_phone_number")
    op.drop_column("User", "address_street")
    op.drop_column("User", "address_locality")
    op.drop_column("User", "name_company_address")
    op.drop_column("User", "address_rl_et_home")
    op.drop_column("User", "address_index")
    op.drop_column("User", "address_area")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "address_area",
            sa.VARCHAR(length=350),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "address_index", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "address_rl_et_home",
            sa.VARCHAR(length=250),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "name_company_address",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "address_locality",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "address_street",
            sa.VARCHAR(length=450),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "address_phone_number",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "name_user_address",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "surname_user_address",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "country_address",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_User_name_company_address",
        "User",
        ["name_company_address"],
        unique=False,
    )
    op.create_index(
        "ix_User_country_address", "User", ["country_address"], unique=False
    )
    op.drop_column("User", "address")
    op.drop_column("User", "date_birthday")
    # ### end Alembic commands ###
