"""Update tables #3

Revision ID: 33dcc52d9d0d
Revises: 0090c127916f
Create Date: 2024-09-05 21:27:16.201821

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33dcc52d9d0d"
down_revision = "0090c127916f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
