"""upd: vacancy table

Revision ID: 35a9dddc3917
Revises: c6ea4f59bdd2
Create Date: 2025-02-02 21:24:18.890321

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35a9dddc3917"
down_revision = "c6ea4f59bdd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Vacancies",
        sa.Column("is_worked", sa.String(length=125), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Vacancies", "is_worked")
    # ### end Alembic commands ###
