"""add: vacancy_req table

Revision ID: 3ddbb312dcdb
Revises: 35a9dddc3917
Create Date: 2025-02-02 21:38:28.474252

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ddbb312dcdb"
down_revision = "35a9dddc3917"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Vacancyrequest",
        sa.Column("name_user", sa.String(length=165), nullable=False),
        sa.Column("email_user", sa.String(length=255), nullable=False),
        sa.Column("telephone_user", sa.String(length=75), nullable=False),
        sa.Column("experience_user", sa.Text(), nullable=True),
        sa.Column("id_vacancy", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_vacancy"], ["Vacancies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Vacancyrequest")
    # ### end Alembic commands ###
