"""upd: user table, added new column - secret_create_key

Revision ID: 4d8fe99a3ae0
Revises: 743b969624ec
Create Date: 2024-10-14 20:35:20.618535

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d8fe99a3ae0"
down_revision = "743b969624ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("secret_create_key", sa.String(length=80), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "secret_create_key")
    # ### end Alembic commands ###
