"""upd: order table added enum for delivery and type buy operations

Revision ID: 51f76568a66b
Revises: b34b36dda0eb
Create Date: 2025-05-04 18:05:59.324504

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51f76568a66b"
down_revision = "b34b36dda0eb"
branch_labels = None
depends_on = None


def upgrade():
    # Сначала создаём тип ENUM
    op.execute("CREATE TYPE typebuy AS ENUM ('NO_BUY', 'BUY')")
    op.execute("CREATE TYPE deliverymethod AS ENUM ('PICKUP', 'EXPRESS', 'STANDARD')")

    # Затем меняем тип столбцов
    op.execute("""
    ALTER TABLE "Order" ALTER COLUMN type_buy TYPE typebuy USING type_buy::typebuy
    """)

    op.execute("""
    ALTER TABLE "Order" ALTER COLUMN delivery_method TYPE deliverymethod USING delivery_method::deliverymethod 
    """)

    op.alter_column(
        "Order",
        "delivery_method",
        existing_type=sa.TEXT(),
        type_=sa.Enum("PICKUP", "EXPRESS", "STANDARD", name="deliverymethod"),
        existing_nullable=True,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order",
        "delivery_method",
        existing_type=sa.Enum(
            "PICKUP", "EXPRESS", "STANDARD", name="deliverymethod"
        ),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "Order",
        "type_buy",
        existing_type=sa.Enum("NO_BUY", "BUY", name="typebuy"),
        type_=sa.VARCHAR(length=125),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
