"""upd: order table, change type date_buy

Revision ID: 596684b4b2d9
Revises: c8a303c5b4cf
Create Date: 2025-05-20 15:57:54.896474

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "596684b4b2d9"
down_revision = "c8a303c5b4cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order",
        "date_buy",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order",
        "date_buy",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
