"""upd: user && order table

Revision ID: 5c56d51453c5
Revises: 51f76568a66b
Create Date: 2025-05-20 14:09:46.013912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c56d51453c5"
down_revision = "51f76568a66b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Order_id_user_fkey", "Order", type_="foreignkey")
    op.create_foreign_key(
        None, "Order", "User", ["id_user"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Order", type_="foreignkey")
    op.create_foreign_key(
        "Order_id_user_fkey", "Order", "User", ["id_user"], ["id"]
    )
    # ### end Alembic commands ###
