"""update user table && added client settings && upd auth router

Revision ID: 5f22dc2c7a8b
Revises: 244c8280f812
Create Date: 2025-01-23 16:12:09.991425

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f22dc2c7a8b"
down_revision = "244c8280f812"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("telephone", sa.String(length=65), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "telephone")
    # ### end Alembic commands ###
