"""Added Admin table

Revision ID: 6db9e4973704
Revises: 3f66ce613e12
Create Date: 2024-06-04 15:12:57.105222

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6db9e4973704"
down_revision = "3f66ce613e12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
