"""update: product table

Revision ID: 6f68899b2f35
Revises: ba2c49e3ba0b
Create Date: 2025-01-27 21:35:33.497417

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f68899b2f35"
down_revision = "ba2c49e3ba0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Product", sa.Column("type_pr", sa.String(length=65), nullable=True)
    )
    op.create_index(
        op.f("ix_Product_type_pr"), "Product", ["type_pr"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Product_type_pr"), table_name="Product")
    op.drop_column("Product", "type_pr")
    # ### end Alembic commands ###
