"""upd: user table, added new column is_active for registration

Revision ID: 743b969624ec
Revises: dadc2a44062a
Create Date: 2024-10-14 20:22:16.654358

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "743b969624ec"
down_revision = "dadc2a44062a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "is_active")
    # ### end Alembic commands ###
