"""update subcategory table

Revision ID: 74a8f72bfe41
Revises: a42dfb0d10e9
Create Date: 2024-09-26 21:48:10.431538

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74a8f72bfe41"
down_revision = "a42dfb0d10e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Subcategory", "id_category", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "Subcategory",
        "id_sub_category",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Subcategory",
        "id_sub_category",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "Subcategory",
        "id_category",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
