"""update product table

Revision ID: 782301dabede
Revises: 74a8f72bfe41
Create Date: 2024-09-27 21:40:44.346797

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "782301dabede"
down_revision = "74a8f72bfe41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product", "id_category", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "Product",
        "id_subcategory_thirst_level",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "Product",
        "id_subcategory_second_level",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product",
        "id_subcategory_second_level",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "Product",
        "id_subcategory_thirst_level",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "Product", "id_category", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
