"""Обновление таблиц пользователя и товаров, и заказов

Revision ID: 8725d33c0942
Revises: fbbee53c3b46
Create Date: 2024-06-19 16:10:02.891067

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8725d33c0942"
down_revision = "fbbee53c3b46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Order", sa.Column("date_buy", sa.Date(), nullable=False))
    op.add_column(
        "Product", sa.Column("date_create_product", sa.Date(), nullable=False)
    )
    op.add_column(
        "Product",
        sa.Column("date_update_information", sa.Date(), nullable=False),
    )
    op.add_column(
        "User", sa.Column("date_registration", sa.Date(), nullable=False)
    )
    op.add_column("User", sa.Column("date_update", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "date_update")
    op.drop_column("User", "date_registration")
    op.drop_column("Product", "date_update_information")
    op.drop_column("Product", "date_create_product")
    op.drop_column("Order", "date_buy")
    # ### end Alembic commands ###
