"""add: product marks table

Revision ID: 894bea32b257
Revises: dfaa5120804b
Create Date: 2025-02-10 03:03:28.101640

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "894bea32b257"
down_revision = "dfaa5120804b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Productmarks",
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id_mark", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_mark"], ["Mark.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["id_product"], ["Product.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "Garage_id_type_moto_fkey", "Garage", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "Garage",
        "Typemoto",
        ["id_type_moto"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "Product_brand_mark_fkey", "Product", type_="foreignkey"
    )
    op.drop_column("Product", "brand_mark")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Product",
        sa.Column(
            "brand_mark", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "Product_brand_mark_fkey",
        "Product",
        "Mark",
        ["brand_mark"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "Garage", type_="foreignkey")
    op.create_foreign_key(
        "Garage_id_type_moto_fkey",
        "Garage",
        "Typemoto",
        ["id_type_moto"],
        ["id"],
    )
    op.drop_table("Productmarks")
    # ### end Alembic commands ###
