"""update tables

Revision ID: 922c75d093e0
Revises: b2a1152df116
Create Date: 2025-01-23 09:17:33.649765

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "922c75d093e0"
down_revision = "b2a1152df116"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Order", sa.Column("price_result", sa.Numeric(), nullable=False)
    )
    op.alter_column(
        "User",
        "main_name_user",
        existing_type=sa.VARCHAR(length=250),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "main_name_user",
        existing_type=sa.VARCHAR(length=250),
        nullable=False,
    )
    op.drop_column("Order", "price_result")
    # ### end Alembic commands ###
