"""upd user table

Revision ID: 9c5e09756cc0
Revises: 5f22dc2c7a8b
Create Date: 2025-01-23 16:20:02.282563

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c5e09756cc0"
down_revision = "5f22dc2c7a8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User", "telephone", existing_type=sa.VARCHAR(length=65), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "telephone",
        existing_type=sa.VARCHAR(length=65),
        nullable=False,
    )
    # ### end Alembic commands ###
