"""Update admin table

Revision ID: a16c76bbf438
Revises: 7621a98ad776
Create Date: 2024-09-05 20:27:46.373634

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a16c76bbf438"
down_revision = "7621a98ad776"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Admin",
        "email_admin",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
    )
    op.alter_column("Admin", "password_user", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("Admin", "date_create", existing_type=sa.DATE(), nullable=True)
    op.alter_column("Admin", "date_update", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Admin", "date_update", existing_type=sa.DATE(), nullable=False)
    op.alter_column("Admin", "date_create", existing_type=sa.DATE(), nullable=False)
    op.alter_column("Admin", "password_user", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "Admin",
        "email_admin",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
    )
    # ### end Alembic commands ###
