"""update order table, added type_buy column

Revision ID: b34b36dda0eb
Revises: f2201f49adfd
Create Date: 2025-05-04 17:31:33.700869

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b34b36dda0eb"
down_revision = "f2201f49adfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Order", sa.Column("type_buy", sa.String(length=125), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Order", "type_buy")
    # ### end Alembic commands ###
