"""upd: order table

Revision ID: b3c551188ee9
Revises: fa1f6469bc4f
Create Date: 2025-05-02 18:47:44.541591

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3c551188ee9"
down_revision = "fa1f6469bc4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Order", sa.Column("transaction_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "Order", sa.Column("user_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "Order",
        sa.Column("telephone_number", sa.String(length=65), nullable=True),
    )
    op.add_column(
        "Order", sa.Column("delivery_method", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Order", "delivery_method")
    op.drop_column("Order", "telephone_number")
    op.drop_column("Order", "user_name")
    op.drop_column("Order", "transaction_id")
    # ### end Alembic commands ###
