"""upd: user table

Revision ID: b8bf6dfa3bc3
Revises: 0bbc933146cf
Create Date: 2025-05-02 15:42:48.470358

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8bf6dfa3bc3"
down_revision = "0bbc933146cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("address_city", sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "address_city")
    # ### end Alembic commands ###
