"""upd: product table

Revision ID: ba2c49e3ba0b
Revises: d6b64806735e
Create Date: 2025-01-27 14:02:52.279748

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba2c49e3ba0b"
down_revision = "d6b64806735e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Product", sa.Column("is_recommended", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Product", "is_recommended")
    # ### end Alembic commands ###
