"""add: cascades

Revision ID: ba9c904d43f5
Revises: 1c00ae8f661b
Create Date: 2025-05-02 22:10:54.582311

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba9c904d43f5"
down_revision = "1c00ae8f661b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Orderproducts_id_order_fkey", "Orderproducts", type_="foreignkey"
    )
    op.drop_constraint(
        "Orderproducts_id_product_fkey", "Orderproducts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "Orderproducts",
        "Order",
        ["id_order"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "Orderproducts",
        "Product",
        ["id_product"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Orderproducts", type_="foreignkey")
    op.drop_constraint(None, "Orderproducts", type_="foreignkey")
    op.create_foreign_key(
        "Orderproducts_id_product_fkey",
        "Orderproducts",
        "Product",
        ["id_product"],
        ["id"],
    )
    op.create_foreign_key(
        "Orderproducts_id_order_fkey",
        "Orderproducts",
        "Order",
        ["id_order"],
        ["id"],
    )
    # ### end Alembic commands ###
