"""added garage table

Revision ID: c6ea4f59bdd2
Revises: 6079a56aa5ea
Create Date: 2025-01-28 03:11:20.853028

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6ea4f59bdd2"
down_revision = "6079a56aa5ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Garage",
        sa.Column("id_model", sa.Integer(), nullable=False),
        sa.Column("id_mark", sa.Integer(), nullable=False),
        sa.Column("id_type_moto", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_mark"],
            ["Mark.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_model"],
            ["Model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_type_moto"],
            ["Typemoto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Garage")
    # ### end Alembic commands ###
