"""add: nullable on user table

Revision ID: c8a303c5b4cf
Revises: 5c56d51453c5
Create Date: 2025-05-20 14:16:10.806766

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8a303c5b4cf"
down_revision = "5c56d51453c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "id_user", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "id_user", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
