"""update tables

Revision ID: c9e11c662607
Revises: 90474608fd6c
Create Date: 2024-10-25 20:53:42.861681

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "c9e11c662607"
down_revision = "90474608fd6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Historybuy_id_user_fkey", "Historybuy", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "Historybuy", "User", ["id_user"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("Model_id_mark_fkey", "Model", type_="foreignkey")
    op.create_foreign_key(
        None, "Model", "Mark", ["id_mark"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("Product_brand_mark_fkey", "Product", type_="foreignkey")
    op.drop_constraint("Product_brand_fkey", "Product", type_="foreignkey")
    op.create_foreign_key(
        None, "Product", "Mark", ["brand_mark"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "Product", "Brand", ["brand"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "Productmodels_id_model_fkey", "Productmodels", type_="foreignkey"
    )
    op.drop_constraint(
        "Productmodels_id_product_fkey", "Productmodels", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "Productmodels",
        "Product",
        ["id_product"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "Productmodels",
        "Model",
        ["id_model"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Productmodels", type_="foreignkey")
    op.drop_constraint(None, "Productmodels", type_="foreignkey")
    op.create_foreign_key(
        "Productmodels_id_product_fkey",
        "Productmodels",
        "Product",
        ["id_product"],
        ["id"],
    )
    op.create_foreign_key(
        "Productmodels_id_model_fkey",
        "Productmodels",
        "Model",
        ["id_model"],
        ["id"],
    )
    op.drop_constraint(None, "Product", type_="foreignkey")
    op.drop_constraint(None, "Product", type_="foreignkey")
    op.create_foreign_key(
        "Product_brand_fkey", "Product", "Brand", ["brand"], ["id"]
    )
    op.create_foreign_key(
        "Product_brand_mark_fkey", "Product", "Mark", ["brand_mark"], ["id"]
    )
    op.drop_constraint(None, "Model", type_="foreignkey")
    op.create_foreign_key(
        "Model_id_mark_fkey", "Model", "Mark", ["id_mark"], ["id"]
    )
    op.drop_constraint(None, "Historybuy", type_="foreignkey")
    op.create_foreign_key(
        "Historybuy_id_user_fkey", "Historybuy", "User", ["id_user"], ["id"]
    )
    # ### end Alembic commands ###
