"""update review table

Revision ID: d59d045c5461
Revises: fcb6621e2955
Create Date: 2024-09-08 16:16:32.529969

"""

# revision identifiers, used by Alembic.
revision = "d59d045c5461"
down_revision = "fcb6621e2955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
