"""update: user table

Revision ID: d6b64806735e
Revises: da5167fb49b7
Create Date: 2025-01-26 20:49:13.635844

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6b64806735e"
down_revision = "da5167fb49b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "surname_user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "surname_user",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
