"""upd: order table

Revision ID: dcecfa77337a
Revises: 172292870c95
Create Date: 2025-05-02 21:39:27.496861

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcecfa77337a"
down_revision = "172292870c95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Order", "count_product")
    op.add_column(
        "Orderproducts",
        sa.Column("count_product", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Orderproducts", "count_product")
    op.add_column(
        "Order",
        sa.Column(
            "count_product", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
