"""update user table

Revision ID: dd026ab228eb
Revises: c9e11c662607
Create Date: 2024-11-29 20:58:40.415462

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dd026ab228eb"
down_revision = "c9e11c662607"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "password_user",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="password_user::bytea",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "password_user",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=60),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
