"""upd: garage table
Revision ID: dfaa5120804b
Revises:
Create Date: 2025-02-10 02:46:08.911844
"""

from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "dfaa5120804b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
