"""upd: brand table

Revision ID: e318ff3098f8
Revises: 3ddbb312dcdb
Create Date: 2025-02-05 14:42:53.890201

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e318ff3098f8"
down_revision = "3ddbb312dcdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Brand", sa.Column("url_photo", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Brand", "url_photo")
    # ### end Alembic commands ###
