"""upd: order table

Revision ID: e7b17a301d94
Revises: b3c551188ee9
Create Date: 2025-05-02 18:50:02.267670

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7b17a301d94"
down_revision = "b3c551188ee9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Order", sa.Column("email_user", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Order", "email_user")
    # ### end Alembic commands ###
