"""add price column in Order Product

Revision ID: ee7e9fbe5401
Revises: dcecfa77337a
Create Date: 2025-05-02 21:49:06.018738

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee7e9fbe5401"
down_revision = "dcecfa77337a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Orderproducts", sa.Column("price", sa.Double(), nullable=True)
    )
    op.alter_column(
        "Orderproducts",
        "count_product",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Orderproducts",
        "count_product",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("Orderproducts", "price")
    # ### end Alembic commands ###
