"""Update other tables, fix nullable parameter in tables

Revision ID: ef6337b7669b
Revises: a16c76bbf438
Create Date: 2024-09-05 20:30:59.457273

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef6337b7669b"
down_revision = "a16c76bbf438"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Product", "other_data", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "Product",
        "date_create_product",
        existing_type=sa.DATE(),
        nullable=True,
    )
    op.alter_column(
        "Product",
        "date_update_information",
        existing_type=sa.DATE(),
        nullable=True,
    )
    op.alter_column(
        "Review",
        "estimation_review",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Review",
        "estimation_review",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "Product",
        "date_update_information",
        existing_type=sa.DATE(),
        nullable=False,
    )
    op.alter_column(
        "Product",
        "date_create_product",
        existing_type=sa.DATE(),
        nullable=False,
    )
    op.alter_column("Product", "other_data", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
