"""Update product table

Revision ID: ef706b45a8a0
Revises: 23c9f0693868
Create Date: 2024-06-09 19:06:20.979024

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef706b45a8a0"
down_revision = "23c9f0693868"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
