"""update order table

Revision ID: f2201f49adfd
Revises: ba9c904d43f5
Create Date: 2025-05-04 16:47:05.466662

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2201f49adfd"
down_revision = "ba9c904d43f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order",
        "transaction_id",
        existing_type=sa.BIGINT(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order",
        "transaction_id",
        existing_type=sa.Text(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
