"""upd: enum

Revision ID: f50b7b76bf3a
Revises: 596684b4b2d9
Create Date: 2025-05-22 16:57:25.038464

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f50b7b76bf3a"
down_revision = "596684b4b2d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM "Order" """)
    op.execute("""
        ALTER TABLE "Order"
        ALTER COLUMN type_buy TYPE TEXT
        USING type_buy::text
    """)
    op.execute("DROP TYPE typebuy")
    op.execute("CREATE TYPE typebuy_new AS ENUM ('CARD', 'CASH')")
    op.execute("""
        ALTER TABLE "Order"
        ALTER COLUMN type_buy TYPE typebuy_new
        USING type_buy::typebuy_new
    """)
    op.execute("ALTER TYPE typebuy_new RENAME TO typebuy")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
