"""Добавление поля для секретного ключа

Revision ID: fbbee53c3b46
Revises: 2036255540ba
Create Date: 2024-06-17 22:06:13.785696

"""

# revision identifiers, used by Alembic.
revision = "fbbee53c3b46"
down_revision = "2036255540ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
