"""Add Product Category table

Revision ID: fcb6621e2955
Revises: 33dcc52d9d0d
Create Date: 2024-09-05 21:40:04.662825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcb6621e2955"
down_revision = "33dcc52d9d0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Productcategory",
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id_category", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_category"],
            ["Category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Productcategory")
    # ### end Alembic commands ###
