"""Добавление поля для секретного ключа

Revision ID: 2036255540ba
Revises: 296b9d254670
Create Date: 2024-06-17 22:05:25.749120

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2036255540ba"
down_revision = "296b9d254670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("secret_update_key", sa.String(length=80), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "secret_update_key")
    # ### end Alembic commands ###
