"""Update photo product

Revision ID: 296b9d254670
Revises: b53172fc1868
Create Date: 2024-06-14 17:07:39.363164

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "296b9d254670"
down_revision = "b53172fc1868"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product",
        "photo_product",
        existing_type=postgresql.BYTEA(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Product",
        "photo_product",
        existing_type=sa.Text(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
