"""Add foreign key in review

Revision ID: 3f66ce613e12
Revises: 7c2d4f1a9fe5
Create Date: 2024-06-01 20:57:06.234892

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f66ce613e12"
down_revision = "7c2d4f1a9fe5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Review", sa.Column("id_product", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "Review", "Product", ["id_product"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Review", type_="foreignkey")
    op.drop_column("Review", "id_product")
    # ### end Alembic commands ###
