"""Добавил адрес в таблицу пользователя

Revision ID: 5231dcf2c593
Revises: 8725d33c0942
Create Date: 2024-06-19 16:52:50.133511

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5231dcf2c593"
down_revision = "8725d33c0942"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("name_user_address", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "User",
        sa.Column(
            "surname_user_address", sa.String(length=200), nullable=True
        ),
    )
    op.add_column(
        "User",
        sa.Column(
            "name_company_address", sa.String(length=200), nullable=True
        ),
    )
    op.add_column(
        "User",
        sa.Column("country_address", sa.String(length=300), nullable=True),
    )
    op.add_column(
        "User",
        sa.Column("address_street", sa.String(length=450), nullable=True),
    )
    op.add_column(
        "User",
        sa.Column("address_rl_et_home", sa.String(length=250), nullable=True),
    )
    op.add_column(
        "User",
        sa.Column("address_locality", sa.String(length=300), nullable=True),
    )
    op.add_column(
        "User", sa.Column("address_area", sa.String(length=350), nullable=True)
    )
    op.add_column(
        "User", sa.Column("address_index", sa.Integer(), nullable=True)
    )
    op.add_column(
        "User",
        sa.Column("address_phone_number", sa.String(length=40), nullable=True),
    )
    op.create_index(
        op.f("ix_User_country_address"),
        "User",
        ["country_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_User_name_company_address"),
        "User",
        ["name_company_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_User_name_company_address"), table_name="User")
    op.drop_index(op.f("ix_User_country_address"), table_name="User")
    op.drop_column("User", "address_phone_number")
    op.drop_column("User", "address_index")
    op.drop_column("User", "address_area")
    op.drop_column("User", "address_locality")
    op.drop_column("User", "address_rl_et_home")
    op.drop_column("User", "address_street")
    op.drop_column("User", "country_address")
    op.drop_column("User", "name_company_address")
    op.drop_column("User", "surname_user_address")
    op.drop_column("User", "name_user_address")
    # ### end Alembic commands ###
