"""Initial migrate

Revision ID: 7c2d4f1a9fe5
Revises: bdd4506ecba2
Create Date: 2024-06-01 19:03:23.195505

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c2d4f1a9fe5"
down_revision = "bdd4506ecba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Category",
        sa.Column("name_category", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Category_name_category"),
        "Category",
        ["name_category"],
        unique=True,
    )
    op.create_table(
        "User",
        sa.Column("email_user", sa.Text(), nullable=False),
        sa.Column("password_user", sa.String(length=60), nullable=False),
        sa.Column("name_user", sa.String(length=100), nullable=True),
        sa.Column("surname_user", sa.String(length=150), nullable=True),
        sa.Column("main_name_user", sa.String(length=250), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Product",
        sa.Column("title_product", sa.String(length=200), nullable=False),
        sa.Column("price_product", sa.Double(), nullable=False),
        sa.Column("quantity_product", sa.Integer(), nullable=True),
        sa.Column("explanation_product", sa.String(length=600), nullable=True),
        sa.Column("article_product", sa.String(length=150), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("other_data", sa.Text(), nullable=False),
        sa.Column("photo_product", sa.LargeBinary(), nullable=False),
        sa.Column("id_category", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_category"],
            ["Category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Review",
        sa.Column("text_review", sa.Text(), nullable=False),
        sa.Column("estimation_review", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Favourite",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Historybuy",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Order",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_product", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_product"],
            ["Product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Order")
    op.drop_table("Historybuy")
    op.drop_table("Favourite")
    op.drop_table("Review")
    op.drop_table("Product")
    op.drop_table("User")
    op.drop_index(op.f("ix_Category_name_category"), table_name="Category")
    op.drop_table("Category")
    # ### end Alembic commands ###
