"""Update product table

Revision ID: 92d868d8dd0e
Revises: ef706b45a8a0
Create Date: 2024-06-09 19:06:54.495709

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92d868d8dd0e"
down_revision = "ef706b45a8a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
