"""Добавил таблицы вакансии и тип работников

Revision ID: b53172fc1868
Revises: 1427b5adf155
Create Date: 2024-06-12 19:33:29.145770

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b53172fc1868"
down_revision = "1427b5adf155"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Typeworker",
        sa.Column("name_type", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Typeworker_name_type"),
        "Typeworker",
        ["name_type"],
        unique=True,
    )
    op.create_table(
        "Vacancies",
        sa.Column("salary_employee", sa.Integer(), nullable=False),
        sa.Column("description_vacancies", sa.Text(), nullable=False),
        sa.Column("id_type_worker", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_type_worker"],
            ["Typeworker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Vacancies")
    op.drop_index(op.f("ix_Typeworker_name_type"), table_name="Typeworker")
    op.drop_table("Typeworker")
    # ### end Alembic commands ###
